import 'package:flutter/material.dart';

class District {
  final String name;
  final List<String> talukas;

  District({required this.name, required this.talukas});
}

class DistrictPage extends StatelessWidget {
  final List<District> districts = [
    District(name: 'Ahmednagar', talukas: [
      'Parner',
      'Loni (Haveli)',
      'Jamgaon',
      'Nepti',
      'Arangaon',
      'Nagapur',
      'Shendi (Pokhardi)',
      'Dongargan',
      'Vambori',
      'Bhingar',
      'Chinchodi (Patil)',
      'Narayan Doh',
      'Madh Pimpri',
      'Mandavgan',
      'Ghogargaon (Tal. Shrigonda)',
      'Mirajgaon',
      'Sakat',
      'Lad Jalgaon',
      'Nagalwadi',
      'Kharvandi (Kasar)'
          'Bheticha vad',
      'Yeli',
      'Avhane Budruk',
      'Miri',
      'Khandgaon (Lohsar)',
      'Sonai',
      'Belapur',
      'Chas (Nali)',
      'Suregaon Sangvi',
      'Sanvatsar',
      'Kokamthan',
      'Puntamba',
      'Naygaon',
      'Naur',
      'Domegram',
      'Domegram Chhinnasthali',
      'Ghumandeo',
      'Bhokar',
      'Khokar',
      'Takli Bhan',
      'Ghogargaon (Tal. Nevasa)',
      'Bel Pimpalgaon',
      'Suregaon (Bhalgaon)',
      'Nevasa',
      'Dusre Galnimb June',
      'Koteshwar',
      'Suregaon (Dahigaon)',
      'Warkhed (Ghat Siddhanath)',
      'Chapadgaon',
      'Ghotan'
    ]),
    District(name: 'Akola', talukas: [
      'Ghatali (Ghatatil Sthaan)',
      'Alegaon',
      'Alegaon',
      'Patur',
      'Barshi Takli',
      'Ghatali',
      'Yelwan',
      'Mana',
      'Lakhpuri'
    ]),
    District(name: 'Amravati', talukas: [
      'Shingnapur',
      'Kholapur',
      'Waki',
      'Ashti',
      'Anjangao (Bari)',
      'Bhankhedi',
      'Rahatgaon',
      'Nandgaon (Peth)',
      'Matulgram',
      'Pujda',
      'Antor',
      'Katsur',
      'Belora',
      'Ridhpur (Rajmath)',
      'Ridhpur (Vajeshwar)',
      'Ridhpur (Bhairavburuj)',
      'Ridhpur (Dwarka Darshan)',
      'Ridhpur (Gudha Sthaan)',
      'Ridhpur (Kshetrakhaj)',
      'Ridhpur (Pivaltaloli)',
      'Dabheri',
      'Talegaon (Shri Chakra. Sthaan)',
      'Talegaon (Shri Go. Sthaan)',
      'Brahmanwada (Dive)',
      'Boraj',
      'Najarpur',
      'Kharala',
      'Talwel',
      'Sawur',
      'Takarkheda (Sambhu)',
      'Rama',
      'Thugaon (Purnanagar)',
      'Asatpur',
      'Vadner (Bhujang)',
      'Kakda',
      'Achalpur',
      'Achalpur (Bor ban)',
      'Achalpur (Charanchari)',
      'Ashtamahasiddhi',
      'Kurha',
      'Deurwada (Kajli)',
      'Deurwada (Kajli) (Narsimha Mandir)',
      'Madhan',
      'Nanori',
      'Sonori',
      'Sonori (Sonjay)',
      'Domak',
      'Ashtoli',
      'Kolvihir',
      'Khed',
      'Pala',
      'Shirkhed (Sthaan No.1)',
      'Shirked (Sthaan No.2)',
      'Shirkhed (Sthaan No.3-9)',
      'Katpur',
      'Akhatwada',
      'Akhatwada (Kalankeshwar Sthaan)',
      'Tivsa (East)',
      'Tivsa (West)',
      'Maldhur',
      'Shendurjana Bazar',
      'Namaskari'
    ]),
    District(name: 'Aurangabad', talukas: [
      'Purangaon',
      'Hingoni',
      'Savakhed (Ganga)',
      'Vanjargaon',
      'Chandegaon',
      'Nagamthan',
      'Hamrapur',
      'Bajathan',
      'Deogaon',
      'Nevargaon',
      'Kanadgaon',
      'Mamdapur',
      'Bagdi',
      'Jamgaon',
      'Gangapur',
      'Galnib June',
      'June Agervadgaon',
      'Paithan',
      'Khadkuli',
      'Sangameshwar',
      'Wadvali',
      'Mayagaon',
      'Navgaon',
      'Hiradpuri',
      'Sawaldabara',
      'Rahatgaon',
      'Kadethan Budruk',
      'Fulshevra',
      'Lasur',
      'Vitkheda',
      'Mategao',
      'Kannad',
      'Hatnur',
      'Ellora',
      'Gadana',
      'Phulambri',
      'Nillod',
      'Sillod',
      'Charner',
      'Karanjkhed',
      'Saigavhan'
    ]),
    District(name: 'Beed', talukas: [
      'Keli Pimpalgaon',
      'Waki',
      'Shiral',
      'Pargaon (Jogeshwari)',
      'Ashti',
      'Matkuli',
      'Sautada (Ramdara)',
      'Patoda',
      'Limba (Ganesh)',
      'Pohicha Deo',
      'Pali',
      'Beed',
      'Kolgaon',
      'Shekta',
      'Chaklamba',
      'Pargaon (Ghogas)',
      'Rokda (Kada)',
      'Panchaleshwar',
      'Khamgaon',
      'BagPimpalgaon',
      'Gevrai',
      'Sangam Jalgaon',
      'Agar Nandur',
      'Mirgaon',
      'Pandhri (Papvinashani)'
    ]),
    District(name: 'Bhandara', talukas: [
      'Bhandara (Kham Talao)',
      'Bhandara (Panch Deuli)',
      'Bhandara (Paanipatra Sthaan)'
    ]),
    District(name: 'Buldhana', talukas: [
      'Masrul',
      'Dodhra',
      'Dodhra',
      'Shendurjan',
      'Lonar',
      'Lonar (Gomukh)',
      'Lonar (Kamalja)',
      'Lonar (Kumareshwar)',
      'Shara',
      'Weni',
      'Mehkar',
      'Anjni Bu.',
      'Vishvi (Isvi)',
      'Chinchale'
    ]),
    District(name: 'Gondia', talukas: ['Sukli (Dakram)']),
    District(name: 'Jalgaon', talukas: [
      'Waghli',
      'Kanashi',
      'Kanashi (Nandani)',
      'Bhadgaon',
      'Bhadgaon',
      'Pachora',
      'Shendurni(1)',
      'Shendurni(2)',
      'Changdeo',
      'Hartale'
    ]),
    District(name: 'Jalna', talukas: [
      'Balegaon',
      'Apegaon',
      'Sashti Pimpalgaon',
      'Domalgaon',
      'Gandhari',
      'Shahagad',
      'Sadegaon',
      'Jogladevi',
      'Ramasgaon',
      'Dhakephal Ahermal',
      'Dhakephal',
      'Karadgaon',
      'Gadhe savargaon',
      'Bhatepuri',
      'Khanepuri',
      'Jalna Mastgarh',
      'Jalna Nagavihir',
      'Jalna Vanadev',
      'Kajla',
      'Dabhadi',
      'Rajur',
      'Bhokardan',
      'Anva',
      'Pimpalgaon (Renukai)',
      'Padmavati',
      'Valsavangi',
      'Jalicha Deo'
    ]),
    District(name: 'Nagpur', talukas: [
      'Katol',
      'Katol (Jamb River)',
      'Mansar',
      'Mansar (Manshila)',
      'Ramtek',
      'Mauda'
    ]),
    District(name: 'Nanded', talukas: [
      'Gopalchavadi (Limbgaon)',
      'Nanded (Naleshwar)',
      'Nanded (Bhaveshwar)',
      'Nanded (Gorakshan)',
      'Gopalchavadi (Cidco)',
      'Raher',
      'Mahur (DevDeveshwar)',
      'Mahur (Jalkrida)',
      'Mahur (Vinzuwala Talav)',
      'Mahur (Vandev)',
      'Mahur  (Dohi Deva Bheti Sthaan)'
    ]),
    District(name: 'Nashik', talukas: [
      'Khopdi',
      'Sinnar',
      'Sinnar (Bhojanta Sthaan)',
      'Tryambak (Tryambakeshwar Temple)',
      'Tryambak (Parvat)',
      'Anjneri',
      'Govardhan (Gangapur)',
      'Nashik (Panchavati)',
      'Nashik (Sundarnarayan)',
      'Aadgaon (Adgaon)',
      'Mouje Sukene',
      'Niphad',
      'Niphad',
      'Shivre',
      'Nandur',
      'Nandur (Madhyameshwar)',
      'Kanlad (Kanlas)'
    ]),
    District(name: 'Satara', talukas: [
      'Phaltan (Janmasthaan)',
      'Phaltan (Sarvatirth)',
      'Phaltan (Avasthan)',
      'Phaltan (Rangshila)',
      'Phaltan (Maltan Tale)',
      'Phaltan (Maltan Datta Mandir)',
      'Phaltan (Maltan Viharan Sthaan)'
    ]),
    District(name: 'Wardha', talukas: ['Bhishnur']),
    District(name: 'Washim', talukas: ['Manglur Pir']),
    District(
        name: 'M.P.',
        talukas: ['Salbardi (Sasa Rakshan)', 'Salbardi (Aasan Sthaan)']),
  ];

  DistrictPage({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Districts',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Districts'),
        ),
        body: ListView.builder(
          itemCount: districts.length,
          itemBuilder: (BuildContext context, int index) {
            return ExpansionTile(
              title: Text(districts[index].name),
              children: <Widget>[
                ListView.builder(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  itemCount: districts[index].talukas.length,
                  itemBuilder: (BuildContext context, int subIndex) {
                    return ListTile(
                      title: Text(districts[index].talukas[subIndex]),
                    );
                  },
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}



/*"Ahmednagar",
    "Akola",
    "Amravati",
    "Aurangabad",
    "Beed",
    "Bhandara",
    "Buldhana",
    "Gondia",
    "Jalgaon",
    "Jalna",
    "Nagpur",
    "Nanded",
    "Nashik",
    "Satara",
    "Wardha",
    "Washim",
    "M.P."
    */